/**
 * SingleStore HTTP API Spec
 * This API allows you to execute SQL statements against a SingleStore database.  It supports all statements that can be run in a direct database connection, and uses conventional data type conversion.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExecOutput model module.
 * @module SingleStore/Client/ExecOutput
 * @version 1.0.0
 */
class ExecOutput {
    /**
     * Constructs a new <code>ExecOutput</code>.
     * @alias module:SingleStore/Client/ExecOutput
     */
    constructor() { 
        
        ExecOutput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExecOutput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:SingleStore/Client/ExecOutput} obj Optional instance to populate.
     * @return {module:SingleStore/Client/ExecOutput} The populated <code>ExecOutput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExecOutput();

            if (data.hasOwnProperty('lastInsertId')) {
                obj['lastInsertId'] = ApiClient.convertToType(data['lastInsertId'], 'Number');
            }
            if (data.hasOwnProperty('rowsAffected')) {
                obj['rowsAffected'] = ApiClient.convertToType(data['rowsAffected'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Returns the last value inserted into an AUTO_INCREMENT column.  May be omitted if irrelevant to the command.
 * @member {Number} lastInsertId
 */
ExecOutput.prototype['lastInsertId'] = undefined;

/**
 * The number of rows affected by the command.
 * @member {Number} rowsAffected
 */
ExecOutput.prototype['rowsAffected'] = undefined;






export default ExecOutput;

