/**
 * SingleStore HTTP API Spec
 * This API allows you to execute SQL statements against a SingleStore database.  It supports all statements that can be run in a direct database connection, and uses conventional data type conversion.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QueryOutputError model module.
 * @module SingleStore/Client/QueryOutputError
 * @version 1.0.0
 */
class QueryOutputError {
    /**
     * Constructs a new <code>QueryOutputError</code>.
     * This key will be specified if an error occurred while streaming the results.  Since we may encounter an error after sending response headers a valid client should always check this field before using a response.
     * @alias module:SingleStore/Client/QueryOutputError
     */
    constructor() { 
        
        QueryOutputError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QueryOutputError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:SingleStore/Client/QueryOutputError} obj Optional instance to populate.
     * @return {module:SingleStore/Client/QueryOutputError} The populated <code>QueryOutputError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueryOutputError();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The error code.
 * @member {Number} code
 */
QueryOutputError.prototype['code'] = undefined;

/**
 * The error message.
 * @member {String} message
 */
QueryOutputError.prototype['message'] = undefined;






export default QueryOutputError;

