/**
 * SingleStore HTTP API Spec
 * This API allows you to execute SQL statements against a SingleStore database.  It supports all statements that can be run in a direct database connection, and uses conventional data type conversion.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RowValue model module.
 * @module SingleStore/Client/RowValue
 * @version 1.0.0
 */
class RowValue {
    /**
     * Constructs a new <code>RowValue</code>.
     * A single value in the result statement.
     * @alias module:SingleStore/Client/RowValue
     */
    constructor() { 
        
        RowValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RowValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:SingleStore/Client/RowValue} obj Optional instance to populate.
     * @return {module:SingleStore/Client/RowValue} The populated <code>RowValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RowValue();

        }
        return obj;
    }


}






export default RowValue;

